version: "4"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGO_DB_URI: $MONGO_DB_URI
      DURATION_LIMIT: $DURATION_LIMIT
      CHANNEL: $CHANNEL
      GROUP: $GROUP
      LOG_GROUP_ID: $LOG_GROUP_ID
      OWNER_ID: $OWNER_ID
      SESSION_NAME: $SESSION_NAME
      SUDO_USERS: $SUDO_USERS
